image: gradle:4.10.2

stages:
- build
- release
- publish
- downstream

build:
  stage: build
  script:
  - gradle clean build -x test

snapshot:
  variables:
    OSSRH_REPO_URL: $SNAPSHOT_OSSRH_REPO_URL
  stage: release
  script:
  - gradle release
  only:
    refs:
      - master

release:
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: release
  script:
  - sed -i "47s/.*/    web3jVersion = '${CI_COMMIT_REF_NAME//release\/}'/" build.gradle
  - gradle -Pversion=${CI_COMMIT_REF_NAME//release\/} release
  when: manual
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/