image: gradle:4.10.2

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
- build
- release
- publish

build-snapshot:
  stage: build
  script:
  - ./gradlew clean build -x test
  artifacts:
    paths:
    - build/libs/**
  only:
    refs:
      - master

release-snapshot:
  allow_failure: false
  variables:
    OSSRH_REPO_URL: $SNAPSHOT_OSSRH_REPO_URL
  stage: release
  script:
  - ./gradlew release -x build
  only:
    refs:
      - master

build-version:
  stage: build
  script:
  - sed -i "47s/.*/    web3jVersion = '${CI_COMMIT_REF_NAME//release\/}'/" build.gradle
  - ./gradlew -Pversion=${CI_COMMIT_REF_NAME//release\/} build -x test
  artifacts:
    paths:
    - build/libs/**
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

release-version:
  allow_failure: false
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: release
  script:
  - sed -i "47s/.*/    web3jVersion = '${CI_COMMIT_REF_NAME//release\/}'/" build.gradle
  - ./gradlew -Pversion=${CI_COMMIT_REF_NAME//release\/} release -x bintrayPublish build
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/

publish-version:
  allow_failure: false
  variables:
    OSSRH_REPO_URL: $RELEASE_OSSRH_REPO_URL
  stage: publish
  script:
    - ./gradlew -Pversion=${CI_COMMIT_REF_NAME//release\/} bintrayPublish
    - ./gradlew -Pversion=${CI_COMMIT_REF_NAME//release\/} githubRelease
  only:
    refs:
      - /^release\/(\d*).(\d*).(\d*)/
