language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build snapshot
    if: branch = master
    script: "./gradlew check jacocoTestReport publish"
  - stage: build release
    if: branch =~ /release/
    script: "./gradlew check publish -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: github release
    if: branch =~ /release/
    script: "./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      openssl aes-256-cbc -K $encrypted_fbd37777c211_key -iv $encrypted_fbd37777c211_iv -in web3j.asc.enc -out web3j.asc -d
    fi
env:
  global:
  - secure: HqHyr3iQoijhjKkjPaRjSWcQ1RoGeED2ZlrMaiYOqJVtaDnC///6bEf0jxDF3c7XTT+trUgL2/uCa3yD2ZcDSlo0W2eB9AtTojwKrzQX66FOwbfB3F6eHuCWGI4uzmL6j9ysWVntUJFUM7mGyDBM7kYvR0iz0LoJP2l84K2TvXwpQaticFifndJ+cKm7fVjPI2zvyDEX/t3zDfGlphBof8h+QuJtF6P0A1+IsUqTcDOqm2JzDqGhNvoaKRnSZ5TKbUCYnMBGyS3laYpjaPPCX9OsOgH+TupnS7b7AGh4wP/iFzCnsClV3Cln3JTGnl1Gr8cMUcfRCbY/lnQrweyn/ARTYyqTQhi7uIWmhXCLMsjDg8jEakFMIHj/5jGN4xlbWlbttjjNQpOP9D3vZP/eouTwK09IlrI8f42H01XWUfV6vGPTV7oraAKlBGd4l56pXOur9TiyvuI87FM5IWHBqtYZ1+iXQmPMKHc5ixHBUz9FrUZgGhMtlFRJWOjvdbUYOl319fF7lSpuo656VyS4P371JbTC/LNeT3e36KxySnsak3HwRQeFUhk7aLbREq4eejiNcIfDqN9vYE+ACUa7k5TXgdG/svp1KvtT6BdPKboQPKc0rF5BCLx9zjlRU1+9w3hhWKxiBV83cgq5RBV0+mD7QSoorJltiju1oQRMqQE=
  - secure: DSbgw9Aw59be3nY27WsFucwO+VKDxtQTttGRdAaU+yDgYo7kFP6Fu5ZtuUOsAXZWg1TephbNN1gxXr7EwnBumDuFmfKBZiNwKI6rHspYjPUs7/1dLBteRaeheamCiww29Bbn5vBGEJf75SP6FChX63Ey4eIkaOl686uSJYR/WD16TzI4nX5bAW7JEcB+gE3PdSrgEJAbVmY2vNiqr66vDOQEo0nxHGHx01f03hNzYYnHGGBQ/+b1XAmxvDjNxyXZkX6fBGYYQhrQ82t2hyROzxACftAMZbXGaMBp82qPQ9RI4LJQRKRWiPaSngJg+N3BIB09vCdakCBm6ZNZ7pW0i6A2X/GTOuS6e9a/1iUD3Tpp38NZIfCZzHE4FfBGCi34E4lxhn/aApeds1ZYP8p3c0O9V1pUqhdljMPL7iTpHWrFKffmtRgKwvKDI5CcBcz/a/zffT8hejLIeuqXRxulmpe/sGziZ3rvBCYLhzmLYh3fp7Wt4q8r0TrkV/fWmTiOw7AM+w7/MAaQ3fhq043QCluuXfkEtAH5OcAWEiP4ZoHOZJAim11nebs+E7KxKh2jOkywxZzd6gAR75fAYW64yREDkKTyoeKV1li/ANQxdr1lsSlbpJ3MEY0+sgpjnFbsDSkFEdMwxTaBoW6cAny8xzpPnsZml1bRSl2b+jQ7yQ4=
  - secure: DsxUKtd1NT+0A8xIcX+Veg75P3uyKB0R7gGU5o2Fo0ppJ9GPpSr9M1Kz7+kwD59MwbYsK0cbyebm9fNOqi4PQlR2DcZ3hvsdeF2orcNcXJAp9nVa9n27VSX6Oe89sFKKsaESkZzsFgHKqWWSFYBTF2dkCqLxt8utfMZhlkEzKqTlr7SvW58Qjv8elmbBsx9y0GMuPmOUj4XpCK4RqzR3YWyELbMzB6gcdbCUy7wOxHhzz/HENC/P5ThSJ8u5nbvmPuCGTQD22jfEVh7L4lkyrIbDud5XeNgK2/YzOZPyF9fdU2VgX4LAIFPdVuiPwA7c2LTEtM0lOA71b02yEF5jcfBHC7aF56WlehpakmKRAMm4nE+JpBRrHRZd74QNTM6N/+cU9/kqTP5OKhn/pNfgRNvZ8bS8/utqNxsl+7AZi3YSYNh/KTR4f7ZnDyLzumn061EbGsRsIjFwkvIiO8z4YvMhVgxbbRSvkC7XtFyNoGE6To9GTsDqDOMianQBLe6Iadl0QuE7+xHtObEzwGizEQcPAG4L6hQYeQflREgu+vOX5vjkuEXFjF2ixyM5mSE5UOQAIqEkofz2xQI/1VRHxU3Hkn62Bjf9jlQFafGD/n3z91mcT1rYJpHgGzv+P5U9qKcY7OQg1d6VZCq9eT44xjLlOHGmKLBUcqWyHhU2JHQ=
  - secure: BEHTxElgwKiuOnXDlts2k4ZFsj3/WBvIwODhwwD9p7jkUwGUZvjIOtI56g6s6jDZ8WOOuL6+CJn6qZ9VJi8AtzEpf0yOhsgtC62/F73zzX35aiM45kcFFscdOvmgcuRYqj7jdtmoQXFiYQoGirJ1Tl8CaxtjxUYYpfiXXRKVCtvmwSLsS5SSv345xTZtIEFBpnAHd3IbdXRDO6CUgS8SR6/SIb16I8Jw86xez15PEYDvVaUGSLSu5gE5zqciW41bMvIwkXmo3E3DHwAFySR+4F9SXpVbqn3M8zcnCiCU/k/O9Gf85Seak+n+mCoHs+Q7DWyiQcqVIj+ai21VTuqXRPCeTsbDgVy7YMffvQq0QXjV3q0HLFqVIQ2d8Uh76M97pFnxSK8KeJ+EDWe/+ggPzHmkLx6ThzwddZtmfQ4V9j6qhPRagvn78jRkggf/m5hJe/I0q7P4TJLJqr8bM06GKKbZ8FYpCM2CYC7JtEn+sAy5uW8x0BDmOBWPBKC4wIHhkYZEzDZdDzfajcnp23jO7Wm0nmzg2aPvQtZ2+j9l1YvOaWbIO4Nk26P9TRZNkqs7OUQwSRYoXcKwMhGAUzJQ2+X0so7e/PDtJDk6nlaP8pMYKzPTT1vnoOSGOKuHC5Qqf58JOk7thYaX4VyKAH8w7Qngo7pWZBvAOnhGWd2APVI=
